kind: Template
apiVersion: v1
labels:
  template: wordpress-template
metadata:
  name: wordpress
  annotations:
    openshift.io/display-name: "WordPress MariaDB Example" 
    description: "An example WordPress application with a MariaDB database."
    tags: "wordpress,php,mariadb,summit"
    iconClass: "icon-php"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: wordpress
    name: mariadb
  spec:
    replicas: 1
    selector:
      app: wordpress
      deploymentconfig: mariadb
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: wordpress
          deploymentconfig: mariadb
      spec:
        containers:
        - env:
          - name: DBNAME
            value: ${DBNAME}
          - name: DBPASS
            value: ${DBPASS}
          - name: DBUSER
            value: ${DBUSER}
          image: 'localhost:5000/mariadb:latest'
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 45
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mariadb
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$DBPASS" mysql -h 127.0.0.1 -u $DBUSER -D $DBNAME
                -e 'SELECT 1'
            timeoutSeconds: 2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wordpress
    name: mariadb
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: wordpress
      deploymentconfig: mariadb
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: wordpress
    name: wordpress
  spec:
    replicas: 1
    selector:
      app: wordpress
      deploymentconfig: wordpress
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: wordpress
          deploymentconfig: wordpress
      spec:
        containers:
        - env:
          - name: DB_ENV_DBNAME
            value: ${DBNAME}
          - name: DB_ENV_DBPASS
            value: ${DBPASS}
          - name: DB_ENV_DBUSER
            value: ${DBUSER}
          image: 'localhost:5000/wordpress:latest'
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 45
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: wordpress
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wordpress
    name: wordpress
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wordpress
      deploymentconfig: wordpress
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: wordpress
    name: wordpress
  spec:
    host: ""
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: wordpress
parameters:
- description: Username for MariaDB user that will be used for accessing the database.
  displayName: MariaDB User
  from: user[A-Z0-9]{3}
  name: DBUSER
  required: true
  value: user
- description: Password for the MariaDB user.
  displayName: MariaDB Password
  from: '[a-zA-Z0-9]{12}'
  name: DBPASS
  required: true
  generate: expression
- description: Name of the MariaDB database accessed.
  displayName: MariaDB Database Name
  name: DBNAME
  required: true
  value: mydb
